---
linux:
  children:
    nginx_proxy:  # Имя подгруппы проксирующего узла
      hosts:
        vm-proxy:
          ansible_host: 84.201.129.65
      vars:
        ansible_user: "admsys"
        ansible_ssh_private_key_file: /home/s21270481/.ssh/VM
        connection_protocol: ssh
        ansible_become: true
        ansible_python_interpreter: /usr/bin/python3

    nginx_web:  # Имя подгруппы для отдающих узлов
      hosts:
        vm-web-1:
          ansible_host: 89.169.157.108
        vm-web-2:
          ansible_host: 46.21.245.102
      vars:
        ansible_user: "admsys"
        ansible_ssh_private_key_file: /home/s21270481/.ssh/VM
        connection_protocol: ssh
        ansible_become: true
        ansible_python_interpreter: /usr/bin/python3
